# Generated by Django 3.0.8 on 2020-07-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comestibles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
